-- Vietnamese content for LanguageMode.VI. REPEATABLE and idempotent: it only fills the *_vi columns added by V8,
-- so it is safe in every environment and re-runs whenever this file changes.
--
-- File name starts with "zz" on purpose: Flyway runs repeatable migrations in alphabetical order of their
-- description, and this one must run AFTER R__dev_seed_data (which creates the rows in dev databases). Rows that do
-- not exist yet are simply not touched.
--
-- The translations are a first draft written for toddlers and should be reviewed by a native speaker. NULL / a
-- missing row means "not translated": the API then serves the English text.

-- Question wording: already authored in game_questions.metadata ->> 'text_vi' by the content seed.
UPDATE game_questions
SET question_text_vi = metadata ->> 'text_vi'
WHERE metadata ->> 'text_vi' IS NOT NULL
  AND question_text_vi IS DISTINCT FROM (metadata ->> 'text_vi');

-- Topics
UPDATE topics t
SET name_vi = v.name_vi, description_vi = v.description_vi
FROM (VALUES
    ('ANIMALS', 'Động vật', 'Gặp gỡ các bạn thú đáng yêu'),
    ('FRUITS', 'Trái cây', 'Ngọt và mọng nước'),
    ('VEHICLES', 'Phương tiện', 'Những thứ biết chạy'),
    ('COLORS', 'Màu sắc', 'Cùng học các màu nào'),
    ('SHAPES', 'Hình khối', 'Hình tròn, hình vuông và nhiều hơn nữa'),
    ('NUMBERS', 'Con số', 'Cùng đếm nhé'),
    ('ALPHABET', 'Chữ cái', 'Học các chữ cái'),
    ('FOOD', 'Đồ ăn', 'Những món ngon để ăn'),
    ('TOYS', 'Đồ chơi', 'Đến giờ chơi rồi'),
    ('CLOTHES', 'Quần áo', 'Chúng ta mặc gì nhỉ?'),
    ('HOME', 'Ngôi nhà', 'Những đồ vật trong nhà'),
    ('NATURE', 'Thiên nhiên', 'Nắng, mưa và cây cối'),
    ('SEA_ANIMALS', 'Động vật biển', 'Cuộc sống dưới đáy biển'),
    ('FARM_ANIMALS', 'Động vật nông trại', 'Các bạn ở trang trại'),
    ('VEGETABLES', 'Rau củ', 'Rau củ tốt cho sức khỏe'),
    ('BODY_PARTS', 'Cơ thể', 'Đầu, vai và nhiều hơn nữa'),
    ('WEATHER', 'Thời tiết', 'Nắng, mưa, tuyết và gió'),
    ('FAMILY', 'Gia đình', 'Những người yêu thương con'),
    ('MUSIC_INSTRUMENTS', 'Âm nhạc', 'Âm thanh và nhịp điệu'),
    ('DAILY_ACTIVITIES', 'Hoạt động hằng ngày', 'Những việc chúng ta làm mỗi ngày')
) AS v(code, name_vi, description_vi)
WHERE t.code = v.code
  AND (t.name_vi IS DISTINCT FROM v.name_vi OR t.description_vi IS DISTINCT FROM v.description_vi);

-- Answer items (letters of the alphabet are the same in both languages: name_vi stays NULL = fallback)
UPDATE answer_items a
SET name_vi = v.name_vi
FROM (VALUES
    ('ANIMALS_CAT', 'Con mèo'),
    ('ANIMALS_DOG', 'Con chó'),
    ('ANIMALS_ELEPHANT', 'Con voi'),
    ('ANIMALS_GIRAFFE', 'Hươu cao cổ'),
    ('ANIMALS_ZEBRA', 'Ngựa vằn'),
    ('ANIMALS_LION', 'Sư tử'),
    ('ANIMALS_RABBIT', 'Con thỏ'),
    ('ANIMALS_COW', 'Con bò'),
    ('ANIMALS_TURTLE', 'Con rùa'),
    ('ANIMALS_MONKEY', 'Con khỉ'),
    ('ANIMALS_PIG', 'Con lợn'),
    ('ANIMALS_BEAR', 'Con gấu'),
    ('ANIMALS_MOUSE', 'Con chuột'),
    ('ANIMALS_FISH', 'Con cá'),
    ('FRUITS_BANANA', 'Quả chuối'),
    ('FRUITS_APPLE', 'Quả táo'),
    ('FRUITS_ORANGE', 'Quả cam'),
    ('FRUITS_GRAPE', 'Quả nho'),
    ('FRUITS_WATERMELON', 'Quả dưa hấu'),
    ('FRUITS_PINEAPPLE', 'Quả dứa'),
    ('FRUITS_STRAWBERRY', 'Quả dâu tây'),
    ('FRUITS_PEAR', 'Quả lê'),
    ('FRUITS_KIWI', 'Quả kiwi'),
    ('FRUITS_PLUM', 'Quả mận'),
    ('FRUITS_LEMON', 'Quả chanh'),
    ('FRUITS_CHERRY', 'Quả anh đào'),
    ('VEHICLES_AIRPLANE', 'Máy bay'),
    ('VEHICLES_BOAT', 'Con thuyền'),
    ('VEHICLES_TRAIN', 'Tàu hỏa'),
    ('VEHICLES_BICYCLE', 'Xe đạp'),
    ('VEHICLES_SCHOOL_BUS', 'Xe buýt trường học'),
    ('VEHICLES_CAR', 'Ô tô'),
    ('VEHICLES_FIRE_TRUCK', 'Xe cứu hỏa'),
    ('VEHICLES_AMBULANCE', 'Xe cứu thương'),
    ('VEHICLES_MOTORCYCLE', 'Xe máy'),
    ('VEHICLES_HELICOPTER', 'Trực thăng'),
    ('VEHICLES_TRACTOR', 'Máy kéo'),
    ('VEHICLES_POLICE_CAR', 'Xe cảnh sát'),
    ('COLORS_BLUE', 'Màu xanh dương'),
    ('COLORS_DARK_BLUE', 'Màu xanh đậm'),
    ('COLORS_YELLOW', 'Màu vàng'),
    ('COLORS_GREEN', 'Màu xanh lá'),
    ('COLORS_RED', 'Màu đỏ'),
    ('COLORS_ORANGE', 'Màu cam'),
    ('COLORS_PURPLE', 'Màu tím'),
    ('COLORS_WHITE', 'Màu trắng'),
    ('COLORS_PINK', 'Màu hồng'),
    ('COLORS_BROWN', 'Màu nâu'),
    ('SHAPES_CIRCLE', 'Hình tròn'),
    ('SHAPES_TRIANGLE', 'Hình tam giác'),
    ('SHAPES_SQUARE', 'Hình vuông'),
    ('SHAPES_RECTANGLE', 'Hình chữ nhật'),
    ('SHAPES_OVAL', 'Hình bầu dục'),
    ('SHAPES_PENTAGON', 'Hình ngũ giác'),
    ('SHAPES_HEXAGON', 'Hình lục giác'),
    ('SHAPES_HEART', 'Hình trái tim'),
    ('SHAPES_STAR', 'Hình ngôi sao'),
    ('NUMBERS_ONE', 'Một'),
    ('NUMBERS_TWO', 'Hai'),
    ('NUMBERS_THREE', 'Ba'),
    ('NUMBERS_FOUR', 'Bốn'),
    ('NUMBERS_FIVE', 'Năm'),
    ('NUMBERS_SIX', 'Sáu'),
    ('NUMBERS_SEVEN', 'Bảy'),
    ('NUMBERS_EIGHT', 'Tám'),
    ('FOOD_SANDWICH', 'Bánh mì kẹp'),
    ('FOOD_PIZZA', 'Pizza'),
    ('FOOD_SOUP', 'Món súp'),
    ('FOOD_ICE_CREAM', 'Kem'),
    ('FOOD_RICE', 'Cơm'),
    ('FOOD_NOODLES', 'Mì'),
    ('FOOD_OMELET', 'Trứng chiên'),
    ('FOOD_CAKE', 'Bánh ngọt'),
    ('FOOD_FRENCH_FRIES', 'Khoai tây chiên'),
    ('FOOD_HONEY', 'Mật ong'),
    ('FOOD_SALAD', 'Rau trộn'),
    ('FOOD_POPCORN', 'Bỏng ngô'),
    ('TOYS_BALL', 'Quả bóng'),
    ('TOYS_TEDDY_BEAR', 'Gấu bông'),
    ('TOYS_TOY_CAR', 'Xe đồ chơi'),
    ('TOYS_BLOCKS', 'Khối xếp hình'),
    ('TOYS_TOY_GUITAR', 'Đàn ghi-ta đồ chơi'),
    ('TOYS_PAPER_PLANE', 'Máy bay giấy'),
    ('TOYS_SPINNER', 'Con quay'),
    ('TOYS_PUZZLE', 'Tranh ghép'),
    ('TOYS_DOLL', 'Búp bê'),
    ('TOYS_DRUM', 'Cái trống'),
    ('TOYS_KITE', 'Con diều'),
    ('CLOTHES_HAT', 'Cái mũ'),
    ('CLOTHES_SHOES', 'Đôi giày'),
    ('CLOTHES_JACKET', 'Áo khoác'),
    ('CLOTHES_SWIMSUIT', 'Đồ bơi'),
    ('CLOTHES_GLOVES', 'Găng tay'),
    ('CLOTHES_SCARF', 'Khăn quàng'),
    ('CLOTHES_RAINCOAT', 'Áo mưa'),
    ('CLOTHES_PANTS', 'Quần dài'),
    ('CLOTHES_SUNGLASSES', 'Kính râm'),
    ('CLOTHES_PAJAMAS', 'Bộ đồ ngủ'),
    ('CLOTHES_SOCKS', 'Đôi tất'),
    ('CLOTHES_BOOTS', 'Đôi ủng'),
    ('CLOTHES_T_SHIRT', 'Áo phông'),
    ('HOME_BED', 'Cái giường'),
    ('HOME_CHAIR', 'Cái ghế'),
    ('HOME_DOOR', 'Cánh cửa'),
    ('HOME_WINDOW', 'Cửa sổ'),
    ('HOME_SPOON', 'Cái thìa'),
    ('HOME_CUP', 'Cái cốc'),
    ('HOME_TOOTHBRUSH', 'Bàn chải đánh răng'),
    ('HOME_REFRIGERATOR', 'Tủ lạnh'),
    ('HOME_LAMP', 'Cái đèn'),
    ('HOME_REMOTE_CONTROL', 'Điều khiển từ xa'),
    ('HOME_SOFA', 'Ghế sofa'),
    ('HOME_TABLE', 'Cái bàn'),
    ('HOME_CLOCK', 'Đồng hồ'),
    ('NATURE_SUN', 'Mặt trời'),
    ('NATURE_MOON', 'Mặt trăng'),
    ('NATURE_RAINBOW', 'Cầu vồng'),
    ('NATURE_RAIN', 'Mưa'),
    ('NATURE_PLANT', 'Cây con'),
    ('NATURE_TREE', 'Cái cây'),
    ('NATURE_SUNLIGHT', 'Ánh nắng'),
    ('NATURE_WIND', 'Gió'),
    ('NATURE_CLOUD', 'Đám mây'),
    ('NATURE_LEAF', 'Chiếc lá'),
    ('NATURE_STAR', 'Ngôi sao'),
    ('NATURE_FLOWER', 'Bông hoa'),
    ('NATURE_MOUNTAIN', 'Ngọn núi'),
    ('NATURE_RIVER', 'Dòng sông'),
    ('SEA_ANIMALS_OCTOPUS', 'Bạch tuộc'),
    ('SEA_ANIMALS_WHALE', 'Cá voi'),
    ('SEA_ANIMALS_SHARK', 'Cá mập'),
    ('SEA_ANIMALS_SEA_TURTLE', 'Rùa biển'),
    ('SEA_ANIMALS_DOLPHIN', 'Cá heo'),
    ('SEA_ANIMALS_STARFISH', 'Sao biển'),
    ('SEA_ANIMALS_JELLYFISH', 'Con sứa'),
    ('SEA_ANIMALS_CRAB', 'Con cua'),
    ('SEA_ANIMALS_TURTLE', 'Con rùa'),
    ('SEA_ANIMALS_FISH', 'Con cá'),
    ('SEA_ANIMALS_SEAL', 'Hải cẩu'),
    ('SEA_ANIMALS_SHRIMP', 'Con tôm'),
    ('FARM_ANIMALS_COW', 'Con bò'),
    ('FARM_ANIMALS_PIG', 'Con lợn'),
    ('FARM_ANIMALS_CHICKEN', 'Con gà'),
    ('FARM_ANIMALS_DUCK', 'Con vịt'),
    ('FARM_ANIMALS_SHEEP', 'Con cừu'),
    ('FARM_ANIMALS_HORSE', 'Con ngựa'),
    ('FARM_ANIMALS_GOAT', 'Con dê'),
    ('FARM_ANIMALS_DOG', 'Con chó'),
    ('FARM_ANIMALS_CAT', 'Con mèo'),
    ('VEGETABLES_CARROT', 'Cà rốt'),
    ('VEGETABLES_BROCCOLI', 'Súp lơ xanh'),
    ('VEGETABLES_TOMATO', 'Cà chua'),
    ('VEGETABLES_CORN', 'Ngô'),
    ('VEGETABLES_POTATO', 'Khoai tây'),
    ('VEGETABLES_CUCUMBER', 'Dưa chuột'),
    ('VEGETABLES_PUMPKIN', 'Bí ngô'),
    ('VEGETABLES_ONION', 'Hành tây'),
    ('VEGETABLES_PEPPER', 'Ớt chuông'),
    ('VEGETABLES_MUSHROOM', 'Nấm'),
    ('VEGETABLES_EGGPLANT', 'Cà tím'),
    ('VEGETABLES_LETTUCE', 'Rau xà lách'),
    ('BODY_PARTS_EYES', 'Đôi mắt'),
    ('BODY_PARTS_EARS', 'Đôi tai'),
    ('BODY_PARTS_NOSE', 'Cái mũi'),
    ('BODY_PARTS_MOUTH', 'Cái miệng'),
    ('BODY_PARTS_HANDS', 'Đôi tay'),
    ('BODY_PARTS_FEET', 'Đôi chân'),
    ('BODY_PARTS_HEAD', 'Cái đầu'),
    ('BODY_PARTS_KNEES', 'Đầu gối'),
    ('BODY_PARTS_SHOULDERS', 'Đôi vai'),
    ('BODY_PARTS_TUMMY', 'Cái bụng'),
    ('BODY_PARTS_FINGERS', 'Ngón tay'),
    ('BODY_PARTS_HAIR', 'Mái tóc'),
    ('WEATHER_SUNNY', 'Trời nắng'),
    ('WEATHER_RAINY', 'Trời mưa'),
    ('WEATHER_SNOWY', 'Trời tuyết'),
    ('WEATHER_WINDY', 'Trời gió'),
    ('WEATHER_CLOUDY', 'Trời nhiều mây'),
    ('WEATHER_STORMY', 'Trời bão'),
    ('WEATHER_RAINBOW', 'Cầu vồng'),
    ('WEATHER_FOG', 'Sương mù'),
    ('WEATHER_HOT', 'Nóng'),
    ('WEATHER_COLD', 'Lạnh'),
    ('WEATHER_HAIL', 'Mưa đá'),
    ('WEATHER_TORNADO', 'Lốc xoáy'),
    ('FAMILY_MOM', 'Mẹ'),
    ('FAMILY_DAD', 'Bố'),
    ('FAMILY_BABY', 'Em bé'),
    ('FAMILY_SISTER', 'Chị gái'),
    ('FAMILY_BROTHER', 'Anh trai'),
    ('FAMILY_GRANDMA', 'Bà'),
    ('FAMILY_GRANDPA', 'Ông'),
    ('FAMILY_UNCLE', 'Chú'),
    ('FAMILY_AUNT', 'Cô'),
    ('FAMILY_PET', 'Thú cưng'),
    ('FAMILY_COUSIN', 'Anh chị em họ'),
    ('FAMILY_FRIEND', 'Bạn bè'),
    ('MUSIC_PIANO', 'Đàn piano'),
    ('MUSIC_GUITAR', 'Đàn ghi-ta'),
    ('MUSIC_DRUM', 'Cái trống'),
    ('MUSIC_VIOLIN', 'Đàn vi-ô-lông'),
    ('MUSIC_FLUTE', 'Cây sáo'),
    ('MUSIC_TRUMPET', 'Kèn trumpet'),
    ('MUSIC_TAMBOURINE', 'Trống lắc tay'),
    ('MUSIC_XYLOPHONE', 'Đàn xylophone'),
    ('MUSIC_MARACAS', 'Maracas'),
    ('MUSIC_BELL', 'Cái chuông'),
    ('MUSIC_HARMONICA', 'Kèn harmonica'),
    ('MUSIC_HARP', 'Đàn hạc'),
    ('DAILY_EATING', 'Ăn cơm'),
    ('DAILY_SLEEPING', 'Đi ngủ'),
    ('DAILY_BRUSHING_TEETH', 'Đánh răng'),
    ('DAILY_BATHING', 'Tắm'),
    ('DAILY_PLAYING', 'Chơi'),
    ('DAILY_READING', 'Đọc sách'),
    ('DAILY_DRAWING', 'Vẽ tranh'),
    ('DAILY_WALKING', 'Đi bộ'),
    ('DAILY_DRESSING', 'Mặc quần áo'),
    ('DAILY_WASHING_HANDS', 'Rửa tay'),
    ('DAILY_SINGING', 'Hát'),
    ('DAILY_COOKING', 'Nấu ăn')
) AS v(code, name_vi)
WHERE a.code = v.code
  AND a.name_vi IS DISTINCT FROM v.name_vi;
